site_name: Hypernate
site_url: https://lf-decentralized-trust-labs.github.io/hypernate
repo_url: https://github.com/LF-Decentralized-Trust-labs/hypernate
repo_name: LF-Decentralized-Trust-labs/hypernate
edit_uri: edit/main/docs/
strict: true

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow

plugins:
  - search
  - offline
  - tags
  - social
  - awesome-pages
  - htmlproofer
  - mike:
      alias_type: symlink
      canonical_version: latest

markdown_extensions:
  - def_list

extra:
  version:
    provider: mike
    default: latest

nav:
  - Home: index.md
  - Guides:
    - cicd.md
    - guides/cicd.md
  - Getting Started:
    - getting-started/index.md
    - getting-started/installation.md
    - getting-started/quickstart.md
  - Concepts:
    - concepts/index.md
    - concepts/registry.md
    - concepts/middleware.md
    - concepts/annotations.md
  - API Reference:
    - api/registry.md
    - api/annotations.md
  - Contributing:
    - contributing/index.md
    - contributing/maintainers.md
  - References:
    - references/citing.md
    - references/architecture.md
  - Glossary: glossary.md
